### ISSUE TITLE
Data.sql file is missing

### ISSUE THREAD

**Issue by krawatworkday** [heroku-reference-apps/ask-pdf#4]
Hi @julianduque after looking at your demo in DX. when i am trying to run this , it is missing data.sql file.
Could you please upload the necessary data.sql

**Comment by julianduque** [comment]
Hey @krawatworkday, thanks for the report. I added the file here: 8fbfa7f

**Comment by krawatworkday** [comment]
Thanks @julianduque . Do we also need **pdf_embeddings** table. If its required, Could you please add that as well.

**Comment by julianduque** [comment]
@krawatworkday it will be created automatically by LangChain

**Comment by krawatworkday** [comment]
> @krawatworkday it will be created automatically by LangChain

Thanks @julianduque .
